import "src/styles/globals.css";
import Head from "next/head";
import { useBgColor } from "src/hooks/useBgColor";
import { useCounter } from "src/hooks/useCounter";
import { useInputArray } from "src/hooks/useInputArray";
import { useItmesChange } from "src/hooks/useItemsChange";

function MyApp({ Component, pageProps }) {
  const counter = useCounter();
  const  InputArray= useInputArray();
  useBgColor();
  const itemsChange = useItmesChange();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} {...InputArray} {...itemsChange}/>
    </>
  );
}

export default MyApp;
